### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by JamilH** [ajhager/libgdx-sbt-project.g8#1]
Hi, I am trying to use your template but I am stuck with the ClassNotFoundException. It seems that it is not adding the android-backend jar to the classes.min.jar. Any suggestions ?  I am using sbt 0.11 with the android-plugin from 0.11 branch

The Logcat output:

D/AndroidRuntime( 2472): >>>>>>>>>>>>>> AndroidRuntime START <<<<<<<<<<<<<<
D/AndroidRuntime( 2472): CheckJNI is ON
D/AndroidRuntime( 2472): --- registering native functions ---
I/jdwp    ( 2472): Ignoring second debugger -- accepting and dropping
I/ethernet( 2472): Loading ethernet jni class
I/ActivityManager( 2031): Starting activity: Intent { act=android.intent.action.MAIN flg=0x10000000 cmp=my.game.pkg/.Main }
D/AndroidRuntime( 2472): Shutting down VM
I/ActivityManager( 2031): Start proc my.game.pkg for activity my.game.pkg/.Main: pid=2478 uid=10051 gids={}
D/dalvikvm( 2472): Debugger has detached; object registry had 1 entries
I/AndroidRuntime( 2472): NOTE: attach of thread 'Binder Thread #3' failed
I/jdwp    ( 2478): Ignoring second debugger -- accepting and dropping
I/UsageStats( 2031): Unexpected resume of my.game.pkg while already resumed in com.android.launcher
W/dalvikvm( 2478): Unable to resolve superclass of Lmy/game/pkg/Main; (10)
W/dalvikvm( 2478): Link of class 'Lmy/game/pkg/Main;' failed
D/AndroidRuntime( 2478): Shutting down VM
W/dalvikvm( 2478): threadid=1: thread exiting with uncaught exception (group=0xb58f6290)
E/AndroidRuntime( 2478): FATAL EXCEPTION: main
E/AndroidRuntime( 2478): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{my.game.pkg/my.game.pkg.Main}: java.lang.ClassNotFoundException: my.game.pkg.Main in loader dalvik.system.PathClassLoader[/data/app/my.game.pkg-1.apk]
E/AndroidRuntime( 2478):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2585)
E/AndroidRuntime( 2478):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2679)
E/AndroidRuntime( 2478):        at android.app.ActivityThread.access$2300(ActivityThread.java:125)
E/AndroidRuntime( 2478):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2033)
E/AndroidRuntime( 2478):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 2478):        at android.os.Looper.loop(Looper.java:123)
E/AndroidRuntime( 2478):        at android.app.ActivityThread.main(ActivityThread.java:4627)
E/AndroidRuntime( 2478):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2478):        at java.lang.reflect.Method.invoke(Method.java:521)
E/AndroidRuntime( 2478):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
E/AndroidRuntime( 2478):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
E/AndroidRuntime( 2478):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 2478): Caused by: java.lang.ClassNotFoundException: my.game.pkg.Main in loader dalvik.system.PathClassLoader[/data/app/my.game.pkg-1.apk]
E/AndroidRuntime( 2478):        at dalvik.system.PathClassLoader.findClass(PathClassLoader.java:243)
E/AndroidRuntime( 2478):        at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
E/AndroidRuntime( 2478):        at java.lang.ClassLoader.loadClass(ClassLoader.java:532)
E/AndroidRuntime( 2478):        at android.app.Instrumentation.newActivity(Instrumentation.java:1021)
E/AndroidRuntime( 2478):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2577)
E/AndroidRuntime( 2478):        ... 11 more
I/Process ( 2478): Sending signal. PID: 2478 SIG: 9
W/ActivityManager( 2031):   Force finishing activity my.game.pkg/.Main
I/ActivityManager( 2031): Process my.game.pkg (pid 2478) has died.
I/UsageStats( 2031): Something wrong here, didn't expect com.android.launcher to be paused

**Comment by ajhager** [comment]
It seems like something has changed in sbt; The gdx.jar is not being included from the common project android depends on. For now you can copy it over to test if that fixes things for you. I am working on a more permanent solution. Thanks for reporting!

**Comment by JamilH** [comment]
Got it working by adding 

```
 unmanagedBase <<= baseDirectory( _ /"src/main/libs" ),     
  unmanagedClasspath in Runtime <+= (baseDirectory) map { bd => Attributed.blank(bd / "src/main/libs") }
```

in Settings.android in build.scala. Also I needed to place the gdx.jar in the libs folder of android project.
