### ISSUE TITLE
apk contains unnecessary files (GWT backend xml files, fonts even if not used, ...)

### ISSUE THREAD

**Issue by aginiewicz** [ajhager/libgdx-sbt-project.g8#28]
I don't know yet how much of this is from how libgdx-sbt is set up with it's multi-project approach, and how much is from android-sbt plugin or can be configured, but I think it is very important to deal with it. I've built simple app that displays text message from txt file in assets directory, this is what files I got:

```
./com/esotericsoftware/TableLayout.gwt.xml
./com/badlogic/gdx/graphics/g3d/shaders/default.fragment.glsl
./com/badlogic/gdx/graphics/g3d/shaders/default.vertex.glsl
./com/badlogic/gdx/utils/arial-15.fnt
./com/badlogic/gdx/utils/arial-15.png
./com/badlogic/gdx.gwt.xml
./lib/armeabi-v7a/libgdx.so
./lib/armeabi-v7a/libandroidgl20.so
./lib/armeabi/libgdx.so
./lib/armeabi/libandroidgl20.so
./AndroidManifest.xml
./message.txt
./library.properties
./assets/message.txt
./META-INF/MANIFEST.MF
./META-INF/CERT.RSA
./META-INF/CERT.SF
./classes.dex
./rootdoc.txt
./resources.arsc
```

from those, following files are most likely not needed:

```
./com/esotericsoftware/TableLayout.gwt.xml
./com/badlogic/gdx.gwt.xml
./message.txt
./rootdoc.txt
```

first, I noticed one file from Scala, "./rootdoc.txt" that I believe shouldn't be there (turns out, the "./library.properties" is [needed](http://stackoverflow.com/questions/8337112/scala-library-in-build-path-doesnt-expose-its-version-android-app-dev)). Then all files from inside assets are copied also to root directory ("./message.txt" + "./assets/message.txt" in this case). There are also some files in "./com" directory. Now with those, while font and shaders are I believe needed, the xml files come from GWT backend, and should be stripped. It should be checked which files from those are actually needed, and find a way to remove what isn't (especially the duplicate resources, space is extremely important on phones, and assets is biggest directory out there!).

**Comment by aginiewicz** [comment]
oh, btw - even if someone uses default shader or default font, I believe we need some mechanics to exclude them by default and include them explicitly in build.scala, so when someone uses his own shader/font, we don't pollute the apk file at all. I never tried such things with android-sbt though :-(

**Comment by aginiewicz** [comment]
What I checked, is that both fonts are needed if you use default constructor for BitmapFont, and both shaders are needed when you use default constructor for ModelBatch, or DefaultShader directly (but ModelBatch is only place where it is used by default, SpriteBatch has it's own shader included as String's in constructor). Other files are definitely junk.

**Comment by aginiewicz** [comment]
I managed to fix duplicate assets in https://github.com/ajhager/libgdx-sbt-project.g8/pull/29, but I have no idea what to do with those *.gwt.xml or rootdoc.txt, or with default shader/font when someone does not use them.

**Comment by aginiewicz** [comment]
I'm afraid, rest of this issues cannot be solved easily yet, until either https://github.com/jberkel/android-plugin/pull/154 or https://github.com/jberkel/android-plugin/pull/150 gets accepted (first one more general, but second one would do too), but I'd leave it open until then, because this is still something to fix when it will be possible.

**Comment by ajhager** [comment]
As long as excluding the default shaders/font wasn't default, I could see the benefit of easily excluding them. Scala already adds quite a bit of meat to each apk, so any slimming is beneficial. I'll keep this issue open as a reminder.

**Comment by aginiewicz** [comment]
I think I found one way to strip stuff from gdx without those pull requests, but it requires some reordering again, and I don't know if it is worth it.
- we need to make Android version unaware of gdx.jar, probably by not placing them it ./lib but in custom directory (like libgdx)
- then we can add them into proguard.cfg like
  
  > -injars common/libgdx/gdx.jar(!**.gwt.xml)

what gives us full control over what to include or not (in this case we strip gwt.xml files, but it is easy to strip **.glsl or **arial** same way). I haven't tested it, nor haven't tested how it will work with desktop. Probably some path setting will be enough. Just an idea this time though. I tested that -injars in proguard cfg works, but haven't tried moving gdx.jar)

**Comment by appamatto** [comment]
The pull requests seem to add complexity. Were you able to solve this problem using just the proguard config?

**Comment by ajhager** [comment]
I am in the process of going through these issues and the latests commits to simplify and clean up. I will make sure to test if this can be solved with a proguard config.

**Comment by aginiewicz** [comment]
@appamatto 
Thanks for looking into this. I tried doing it with proguard config only back two months ago - but without luck. Adding extra -injars to options failed, because it included most of the stuff twice, so inclusion with less files was redundant. I haven't found any option that allowed to modify previously included -injars directive, or change inclusion of files inside. This might be due to my rather low proguard experience though. What could serve as a workaround when options would be enough - if there was easy way to stop sbt from adding -injars for specific jar files, then we can add it on options line and it would be ok. Is it currently possible with android-sbt?

**Comment by appamatto** [comment]
@aginiewicz I added a filtering mechanism last week, did you try that?

**Comment by aginiewicz** [comment]
I believe this filtering mechanism will fix it, but I will test it for sure after next snapshot release of 0.7 and after we update this template to 0.7.x.

**Comment by ajhager** [comment]
Is this in a place where it can be tested now?

**Comment by appamatto** [comment]
Yep! Let me know if it works for you. It should be in the current 0.7.1-SNAPSHOT.

**Comment by ajhager** [comment]
No longer using sbt-android.
