### ISSUE TITLE
android-tests should use same proguard.cfg and libgdx jars as android

### ISSUE THREAD

**Issue by aginiewicz** [ajhager/libgdx-sbt-project.g8#31]
I just found out, that instrumentation tests do not have access to android-defined proguard.cfg or libgdx jars copied into it's directory. Probably some tweaking of directory options is needed.

**Comment by ajhager** [comment]
Having a separate project for android-tests has been bugging me anyway. Hopefully we can find a way to merge it into the android project like it normally would be. I'll be exploring this today.

**Comment by aginiewicz** [comment]
I made some preparations here: https://github.com/ajhager/libgdx-sbt-project.g8/pull/32 - it still has some warnings in proguard, but uses correct file.

**Comment by aginiewicz** [comment]
after some messing with code, I now believe this was invalid request. #32 contains commit that removes all warnings reported by proguard during tests creation. I created small and simple testing application that does not contain libgdx nor application. Instead, it uses device-installed application and tests it as whole, thus all dependencies are included there.

It is easy to verify it works that way, when you test with application installed it works, when you test with application uninstalled, it fails saying "Unable to find instrumentation target package".

Seems I was misunderstanding how instrumentation tests work after all. Now it is clear. No libgdx should be included, and it should use different proguard.cfg. Those tests are only to test application lifecycle.
