### ISSUE TITLE
Changes in libgdx distribution, need better extraction mechanics

### ISSUE THREAD

**Issue by aginiewicz** [ajhager/libgdx-sbt-project.g8#34]
Recently distribution of libgdx files changed. There are two important things:
- there are now Android x86 .so files. While x86 is rare on real devices, x86 based emulator works very efficiently (still not sure if it runs though, it isn't that important), but...
- there is no more libandroidgl20.so file, which is copied "by name" in build.sbt

While first change can be ignored for the time being (there is still no gdx-audio on x86), second one I think will break update-gdx for nightlies when first one with this change will be uploaded. Unfortunately simple remove of this file, will break stable releases, so I think better extraction mechanics is needed.

source: http://www.badlogicgames.com/wordpress/?p=3103

**Comment by ajhager** [comment]
I will look into this tomorrow. Seems like a pretty simple fix. Thanks.

**Comment by aginiewicz** [comment]
Actually, there is no issue - because filtering approach takes care of this - if there is no libandroidgl20.so file in jar, there is no error, because on all files this filter is false, so it's ok. Current code handles well both current snapshots and older stable releases, so there is no need to change it.
