### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Kamek** [ajhager/libgdx-sbt-project.g8#36]
I'm new to sbt, and I keep getting an error when using the template/ When I try to update gdx or run desktop I get this:
`[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scala-sbt#sbt-android-plugin;0.7.1-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that th
ese dependencies exist with the requested attributes.
[warn]          org.scala-sbt:sbt-android-plugin:0.7.1-SNAPSHOT (sbtVersion=0.13
, scalaVersion=2.10)
[warn]
`

I have built the android plugin and it put it in %HOME%.ivy2 someplace, but it looks like my gdx game can't find the android plugin. Can anyone help me?

**Comment by aginiewicz** [comment]
Avoid using sbt 0.13, sbt-android seems to be not ready yet: https://github.com/jberkel/android-plugin/issues/190

**Comment by Kamek** [comment]
Is there any other way I can use the template without the android plugin? I'm not developing for android, but libGDX might depend on some android code I'm not sure. If so how can I do that?

**Comment by aginiewicz** [comment]
Just downgrade SBT to version 0.12.x for now, and it should work.

I've also noticed, that you updated sbt-android-plugin to 0.7, please keep it at version 0.6.x for now, like in code generated by template. Version that is partially updated to 0.7 version of plugin is in my branch of libgdx-sbt project, but instrumentation tests does not work yet (if you do not use tests it is already OK to use)

**Comment by Kamek** [comment]
K thanks man, keep up the good work!

**Comment by Kamek** [comment]
Ok I've downgraded sbt and changed the plugin version, now I get this:

```
C:\Users\Kamek\bin\my-game>sbt "project desktop" run
←[0m[←[0minfo←[0m] ←[0mLoading project definition from C:\Users\Kamek\bin\my-gam
e\project←[0m
←[0m[←[0minfo←[0m] ←[0mCompiling 1 Scala source to C:\Users\Kamek\bin\my-game\pr
oject\target\scala-2.9.2\sbt-0.12\classes...←[0m
←[0m[←[31merror←[0m] ←[0mC:\Users\Kamek\bin\my-game\project\build.scala:4: objec
t scalasbt is not a member of package org←[0m
←[0m[←[31merror←[0m] ←[0mimport org.scalasbt.androidplugin._←[0m
←[0m[←[31merror←[0m] ←[0m           ^←[0m
←[0m[←[31merror←[0m] ←[0mone error found←[0m
←[0m[←[31merror←[0m] ←[0m(compile:←[31mcompile←[0m) Compilation failed←[0m
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? i
←[0m[←[33mwarn←[0m] ←[0mIgnoring load failure: no project loaded.←[0m
←[0m[←[31merror←[0m] ←[0mNo project loaded←[0m
←[0m[←[31merror←[0m] ←[0mproject desktop←[0m
←[0m[←[31merror←[0m] ←[0m       ^←[0m
```

**Comment by Kamek** [comment]
Never mind, my bad. I got it working. Go ahead and close this.
