### ISSUE TITLE
idea: simplify adding macros

### ISSUE THREAD

**Issue by aginiewicz** [ajhager/libgdx-sbt-project.g8#38]
Macros are new feature of Scala 2.10.x, and they are very very useful on Android. Thanks to macros I was able to create game entity system that was 100% type safe, managers were independent on components and it did not use reflection, or needed lot of writing.

I propose adding two projects on top of common - engine and macros. Engine can then contain game independent code (and we all have some!), macros can contain well, macros, and common the game itself. With desktop/android/ios containing platform specific parts.

Why split into extra engine and macros? Because:
- macros needs to be compiled before they can be used, so they need to be above common
- macros require reflection at compile time, so we do not want to depend on it directly, we need it as provided dependency (used at run-time, but not included)
- macros generate code so they need access to some parts of game code, which common needs access too - this common code can be well defined as engine.

That way macros and common depend on engine, but engine has macros as only provided dependency.

Why I propose including this change in libgdx-sbt-project? Because it needs some modifications and configuration:
- adding extra projects and correct dependencies (provided dependency vs dependency)
- changing update-gdx to extract files into engine instead of common

and it isn't obvious what needs to be done at first. I've already tested such setup in my projects and it works like a charm, so if we decide to include it (and after merge of sbt-android 0.7) I will prepare pull request with those changes.

**Comment by aginiewicz** [comment]
for starter, we can also add section to readme about "How to integrate Scala macros" and describe needed changes

**Comment by ajhager** [comment]
I am not convinced that the added complexity would be worth it (yet), but I am very interested in seeing a pull request and/or seeing examples of how you are using Macros.  Instead of putting information about it in the README, I would like to see it in a wiki page. The README is already getting long, and I will soon be moving info already there into wiki pages.  Then we can just link to the info pages from the README file.

**Comment by aginiewicz** [comment]
Right now I moved macros to separate package and it almost works like it should, but android-plugin interprets provided dependencies too eagerly: https://github.com/jberkel/android-plugin/issues/198 - anyway when I worked with them "in-project" I had to create new project with common code (engine) and one with macro code (macros), then "common" depended on "engine" and provided "macros".

```
lazy val engine = Project(
  "engine",
  file("engine"),
  settings = Settings.common ++ Seq( name := "specgine"))

lazy val macros = Project(
  "macros",
  file("macros"),
  settings = Settings.macros ++ Seq(name := "specgine-macros"))
  .dependsOn(engine)

lazy val common = Project(
  "common",
  file("common"),
  settings = Settings.common ++ Seq(name := "pong"))
  .dependsOn(engine, macros % "provided")
```

macros simply added library dependency to common settings:

```
lazy val macros = common ++ Seq(
  libraryDependencies <+= (scalaVersion)("org.scala-lang" % "scala-reflect" % _)
)
```

this is long story short, there were some other small modifications. I think you are right, it isn't that important to include it in template by default, and after 2 months of work it turned out to be easier than when I opened this ticket. I think we can close this now
