### ISSUE TITLE
Explore the options for making deskop, platform specific builds.

### ISSUE THREAD

**Issue by ajhager** [ajhager/libgdx-sbt-project.g8#52]
Are there sbt plugins for packaging into osx .app, windows .exe, and linux .deb files? Can those be used with the desktop proguard stuff?

**Comment by aginiewicz** [comment]
Hmm... I know only about one plugin to package natives, https://github.com/sbt/sbt-native-packager - but I don't think it will be compatible with proguard unfortunately.

**Comment by aginiewicz** [comment]
I think that https://github.com/libgdx/packr is the way to go, specially that it is kind of official for libgdx

**Comment by aginiewicz** [comment]
The pro of using https://github.com/libgdx/packr is that it takes .jar as input, so already working jar generated using proguard (with bundled scala and gdx and .so files and assert ...) should be easy to throw in, and it should "just work", like any other jar generated by java. We only need to add sbt task to build this, with "assembly" as dependency.

**Comment by aginiewicz** [comment]
Another nice thing - it seems it filters libraries for other platforms as well: https://github.com/libgdx/packr/blob/master/src/main/java/com/badlogicgames/packr/Packr.java#L209 - when I have some time I will try to make installer task based on this.

**Comment by ajhager** [comment]
This is something Packr handles quite well, and doesn't need any support from us.
