### ISSUE TITLE
Make it easy to add libgdx extension libs like freetype and bullet.

### ISSUE THREAD

**Issue by ajhager** [ajhager/libgdx-sbt-project.g8#56]

**Comment by aginiewicz** [comment]
I was thinking about it (I will need freetype for my project pretty soon) and I think that https://github.com/ajhager/libgdx-sbt-project.g8/issues/48 will be critical here - it would be then simple changing key from false to true and running update to extract needed natives.

**Comment by aginiewicz** [comment]
Technically now it is only adding line to maven dependencies and native extractions - I guess it is as simple as it can get, it only needs wiki documentation now. Don't you think?

**Comment by aginiewicz** [comment]
duplicate of https://github.com/ajhager/libgdx-sbt-project.g8/issues/53
