### ISSUE TITLE
common/assets doesn't appear to be configured correctly.

### ISSUE THREAD

**Issue by photex** [ajhager/libgdx-sbt-project.g8#62]
Hello, using this template if I put a file in common/assets, I'm unable to locate it with Gdx.files.local or Gdx.files.internal.

Would someone clarify the expected way to access files in common/assets?

Thanks!

**Comment by aginiewicz** [comment]
it works for me, assets are copied to right places in current version of template. I'm accessing them normally using Internal. On what platform you try to use it, and what names you use? For example, I have "logo.png" in common/assets and I'm able to access them on Desktop and Android using Gdx.files.internal("logo.png")

**Comment by photex** [comment]
I'm developing on Linux with Ensime and Emacs.

I'm trying to load a file named "entities.json". I tested with a png and that worked just fine so this isn't an issue with the template. Sorry! :)
