### ISSUE TITLE
Allow configuring either libgdx 0.9.9 stable or libgdx snapshot.

### ISSUE THREAD

**Issue by ajhager** [ajhager/libgdx-sbt-project.g8#66]

**Comment by aginiewicz** [comment]
I think this one can be closed as fixed by https://github.com/ajhager/libgdx-sbt-project.g8/pull/67 - because it what remains is making it easily switchable after template is built, I think it is covered by https://github.com/ajhager/libgdx-sbt-project.g8/issues/48 (so either fixed or duplicate).

**Comment by ajhager** [comment]
Indeed, fixed by #67
