### ISSUE TITLE
Remove dependency of conscript and giter8 to ease usable on windows.

### ISSUE THREAD

**Issue by ajhager** [ajhager/libgdx-sbt-project.g8#7]

**Comment by aginiewicz** [comment]
I think giter8 is cool, why not let it be and make Windows people sort it out themselves?

For people who cannot use command line (oh how they will use SBT then?), Typesafe is doing its new "Typesafe Activator" ( http://typesafe.com/platform/getstarted ). For now it only supports 4 official g8 templates, but as it says on main page when you start it, "Community created templates & plugins are coming soon!". That is better way to make libgdx-sbt accessible to Windows people I think (especially that it _will_ happen by itself, and it does not _decrease usability_ of this template for example on linux, where doing "g8 ajhager/libgdx-sbt-project" is all, now that's usability :D)

**Comment by ajhager** [comment]
Thanks for pinging this issue. I hadn't noticed that Activator supported g8 templates, and I think that is a great reason to keep using giter8. The main issue I had with using it was Conscript was a bear to install on windows, but it seems they have a graphical installer jar now.
