### ISSUE TITLE
Explore moving to https://github.com/pfn/android-sdk-plugin and sbt 0.13.x

### ISSUE THREAD

**Issue by ajhager** [ajhager/libgdx-sbt-project.g8#74]

**Comment by aginiewicz** [comment]
As far as I've already investigated, pfn will require us to move assets back to android directory - I haven't found any setting to set custom asset path like mainAssetsPath in current plugin, and only configuration of layout that I've found is selecting between ProjectLayout.Ant and ProjectLayout.Gradle, that are subclasses of sealed trait ProjectLayout (so we cannot define our own project layout) - https://github.com/pfn/android-sdk-plugin/blob/master/src/keys.scala#L216

Nonetheless, adapting Gradle project layout can have its benefits - like easier integration with IDE plugins (it is kind of official new Android build tool now) - and sharing layout with default Libgdx template. The layout from Libgdx template seems to be compatible with android-sdk-plugin, at least at first glance.

I'd say we might investigate changing layout to Gradle after all, but to keep changes gradual, keep current plugin for now (to test it a bit).

**Comment by ajhager** [comment]
I certainly willing to explore this option.

I have also looked around and found forks of https://github.com/jberkel/android-plugin that have already upgraded it to support 0.13.x.  Is the project no longer maintained? There are 8 PRs, although none of them are to upgrade to the newest sbt.

**Comment by aginiewicz** [comment]
another reason to switch to 0.13. sbt 0.12 uses scala 2.9, which does not work with jdk8, that was recently released. It means, that if someone has jdk8 he cannot use project, even if apk would compile due to -source and -target set to java 6.

**Comment by photex** [comment]
https://github.com/molikto/android-plugin/blob/master/README.md

Not sure if relevant but seems like a possible option.

**Comment by aginiewicz** [comment]
I have working prototype with desktop+android, but I have to port few missing features (but, working apk is build). I hope to finish it within few days, so stay tuned for pull request :)

I will also switch to layout used by official gdx project template, so we can just copy project dir with build.scala and plugins.sbt, translate .java to .scala and all should work!

Other thing that I tested was x86 build - and yes, it runs in emulator quite well :)

**Comment by ajhager** [comment]
I am so excited you are working on this! So exciting. Can't wait to try it out.

**Comment by aginiewicz** [comment]
See https://github.com/ajhager/libgdx-sbt-project.g8/pull/79 - unfortunatelly without iOS plugin, will you be able to fill in this gap?

**Comment by aginiewicz** [comment]
See https://github.com/ajhager/libgdx-sbt-project.g8/issues/80 for follow-up on iOS.
