### ISSUE TITLE
HTML5 Support

### ISSUE THREAD

**Issue by PhoenixWright** [ajhager/libgdx-sbt-project.g8#82]
I was wondering what it would take to enable HTML5 support for this project, or if that is even possible.

**Comment by aginiewicz** [comment]
Libgdx uses Google GWT which isn't compatible with Scala as far as I know, so I doubt it will be possible. Maybe, if someone creates Scala.JS backend for Libgdx, which would be possible, but too big for me.

**Comment by ajhager** [comment]
Yeah, I have explored this quite a bit in the past (others as well.) Every 'solution' is going to end up being a lot of work. Scala.JS can't compile java code. There are some abandoned projects that compile Java to Scala and [scalagen](https://github.com/mysema/scalagen) looks the most robust. Then Scala.JS could compile that (perhaps.) A Scala.JS wrapper of an automatically wrapped GWT JSNI interface to libgdx is one of my wackier ideas.

**Comment by aginiewicz** [comment]
I think that this should bypass GWT at all, and do WebGL directly - i.e. by providing new backend, not using existing one. It should be even simpler that trying to get in line with GWT. Anyway, I can barely imagine size of such project :)

**Comment by ajhager** [comment]
Yeah, if scalagen is able to compile the general libgdx Java code, a separate backend written in Scala.JS would work best. Time for my yearly disappointing stab at this. :)

**Comment by PhoenixWright** [comment]
Interesting. Thanks for the info! Not a deal breaker for me by any means, and thanks for this project.

**Comment by ajhager** [comment]
It doesn't look like this will be coming any time soon.

**Comment by JustinMullin** [comment]
The TeaVM team has a prototype LibGDX backend working: https://github.com/konsoletyper/teavm-libgdx.  Live example here: http://teavm.org/live-examples/libgdx-demo-invaders/.  Sounds like it's not production ready yet, but might be the ticket here.
