### ISSUE TITLE
sbt assembly fails on Mac OS

### ISSUE THREAD

**Issue by i-am-the-slime** [ajhager/libgdx-sbt-project.g8#88]
Trying to do sbt assembly.
It does not find /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/lib/rt.jar because that isn't there. I read that this file is called classes and sits in a different folder on OS X. So I made a link:

```
cd /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/lib
sudo ln /System/Library/Frameworks/JavaVM.framework/Classes/classes.jar rt.jar
```

Then, I always get:
`Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
[error]     at java.util.Arrays.copyOfRange(Arrays.java:3209)`

I made an ~/.sbtconfig like this:
`SBT_OPTS="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:PermSize=2048M -XX:MaxPermSize=4096M"`

No luck, though.

**Comment by aginiewicz** [comment]
As for flags, Xmx is maximum heap size and Xms is initial heap size, PermSize and MaxPermSize refer to permanent space, for classes, methods and such. Try adding -Xmx512m or higher. Also, check what is your heap size when starting scala from sbt, do something like:

```
[giniu@raven3 tmp]$ sbt
[info] Loading global plugins from /home/giniu/.sbt/0.13/plugins
[info] Set current project to tmp (in build file:/tmp/)
> console
[info] Updating {file:/tmp/}tmp...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Starting scala interpreter...
[info] 
Welcome to Scala version 2.10.4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_67).
Type in expressions to have them evaluated.
Type :help for more information.

scala> Runtime.getRuntime().maxMemory()/1024.0/1024.0
res0: Double = 1365.5
```

**Comment by i-am-the-slime** [comment]
Here's the setting I left yesterday:
`SBT_OPTS="-Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=4G -Xss2M"`

At least now I know, that these settings are being picked up:
And this is the result:
`scala> Runtime.getRuntime().maxMemory()/1024.0/1024.0
res0: Double = 8175.375`

It even happens on the untouched base project: 

```
[error] Warning: rx.ops.AkkaScheduler: can't find referenced class akka.actor.ActorSystem
[error] Warning: rx.ops.AkkaScheduler: can't find referenced class akka.actor.ActorSystem
[error] Warning: rx.ops.AkkaScheduler: can't find referenced class akka.actor.Scheduler
[error] Warning: rx.ops.AkkaScheduler: can't find referenced class akka.actor.Scheduler
[error] Warning: rx.ops.AkkaScheduler: can't find referenced class akka.actor.ActorSystem
[error] Warning: rx.ops.AkkaScheduler: can't find referenced class akka.actor.ActorSystem
[error] Warning: rx.ops.AkkaScheduler: can't find referenced class akka.actor.ActorSystem
```

I am starting to think that my `rt.jar` workaround isn't really a workaround.

**Comment by i-am-the-slime** [comment]
It seems that adding the middle line to Build.scala helps: 

```
    fork in Compile := true,
    javaOptions in Compile := Seq("-Xmx2G"),
    unmanagedResourceDirectories in Compile += file("android/assets"),
```

**Comment by i-am-the-slime** [comment]
Okay, so here are the steps to fix this:
1. Create a symbolic link for rt jar:

```
cd /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/lib
sudo ln -s ../../Classes/jsse.jar .
sudo ln -s ../../Classes.jar rt.jar
```
1. Add this to your `project/build.scala`:
   `javaOptions in Compile := Seq("-Xmx2G"),` (after `fork in Compile := true`)
2. Append this to `core/proguard-project.txt`
   `-dontwarn rx.ops.AkkaScheduler`  (this is probably specific to a library I am using)
