### ISSUE TITLE
IntelliJ IDEA integration - incorrect source root directory

### ISSUE THREAD

**Issue by pkoperek** [ajhager/libgdx-sbt-project.g8#90]
Hi,

After generating IDEA project files it turns out that `android/src` directory is marked as `Source Root` instead of `android/src/main/scala`. I tried to fix it with adding 

```
scalaSource in Compile := baseDirectory.value / "src/main/scala/"
scalaSource in Test := baseDirectory.value / "src/test/scala/"
```

to `Settings.android` in `build.scala` - but for some reason it didn't work.

Tbh I'm not sure whether this is a template issue or rather android-sdk-plugin problem (feel free to close this issue if so). 
Sorry if this is something obvious - I'm a newcomer to scala/sbt world :)

Regards

**Comment by aginiewicz** [comment]
Sorry, I don't know anything about Idea (nor ScalaIDE) projects, for all my projects vim+sbt are enough. Probably someone with more experience can shed some light on it

**Comment by pkoperek** [comment]
I managed to solve this (and couple other IntelliJ-related) bugs on my own - I've opened a PR for original repo. Feel free to accept/close.
