### ISSUE TITLE
HTML/JS target?

### ISSUE THREAD

**Issue by aquach** [ajhager/libgdx-sbt-project.g8#96]
There doesn't seem to be a html project, so using this template doesn't let you target HTML/JS. Adding it would be greatly appreciated!

**Comment by aginiewicz** [comment]
Would be great, but is outside of scope unfortunately. It was already considered in https://github.com/ajhager/libgdx-sbt-project.g8/issues/82

**Comment by aquach** [comment]
My bad, sorry. Yeah, Scala doesn't mix well with GWT.
